# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.184, name: ZERO},
    {id: 1, size: 0.429, name: ONE},
    {id: 2, size: 1.000, name: TWO},
    {id: 3, size: 0.184, name: THREE},
    {id: 4, size: 0.429, name: FOUR},
    {id: 5, size: 1.000, name: FIVE}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
     {
       name: 'landing_pad_1',
       layout:
         [
           {id: 0, size: 0.184, x:  0.00, y:  0.00, z: 0.00, qw: 1.00, qx: 0.00, qy: 0.00, qz: 0.00},
           {id: 1, size: 0.429, x:  0.00, y:  0.00, z: 0.00, qw: 1.00, qx: 0.00, qy: 0.00, qz: 0.00},
           {id: 2, size: 1.000, x:  0.00, y:  0.00, z: 0.00, qw: 1.00, qx: 0.00, qy: 0.00, qz: 0.00}
         ]
     },
     {
       name: 'landing_pad_2',
       layout:
         [
           {id: 3, size: 0.184, x:  0.00, y:  0.00, z: 0.00, qw: 1.00, qx: 0.00, qy: 0.00, qz: 0.00},
           {id: 4, size: 0.429, x:  0.00, y:  0.00, z: 0.00, qw: 1.00, qx: 0.00, qy: 0.00, qz: 0.00},
           {id: 5, size: 1.000, x:  0.00, y:  0.00, z: 0.00, qw: 1.00, qx: 0.00, qy: 0.00, qz: 0.00}
         ]
     }
  ]


